### ISSUE TITLE
Add new play screen

### ISSUE THREAD

**Issue by chico** [OttoDIY/OttoDIYApp#8]
![Otto_Play_Design](https://user-images.githubusercontent.com/16405/59107382-66f0bf80-8930-11e9-8fdd-147613398731.png)

**Comment by chico** [comment]
@cparrapa @jarsoftelectrical I will get started on this screen hopefully next week & then hand it over to you guys once the UI is ready.

**Comment by cparrapa** [comment]
Great i just added all the icons 1x, 2x, 3x .png  needed for this screen, ready to merge here: https://github.com/OttoDIY/OttoDIYApp/pull/7 ready to merge let me know if needs something else.
